### ISSUE TITLE
get_throttling_function_name

### ISSUE THREAD

**Issue by lucasdavid47** [LatentFreedom/youtube-downloader#1]
![image](https://user-images.githubusercontent.com/33765469/166138624-5dfaf25e-8ebc-46e4-9161-af44754b0d45.png)
I get the following error when i try to download a playlist.
get_throttling_function_name: could not find match for multiple

**Comment by LatentFreedom** [comment]
I am assuming you have the most recent pytube version. This can be fixed by updating the pytube lib's cipher.py file. check out this link and let me know if you have more questions. [https://www.codegrepper.com/](https://www.codegrepper.com/code-examples/python/pytube.exceptions.RegexMatchError%3A+get_throttling_function_name%3A+could+not+find+match+for+multiple)

**Comment by lucasdavid47** [comment]
By manually change the cipher.py file it worked, thanks a lot.
Lucas.
